### ISSUE TITLE
Spurious instructions / .py class files already exist in master

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-classes-and-instances-lab#1]
These instructions are spurious

_So without further ado, create three files in this folder: ride.py, driver.py, and passenger.py. In each of these, define an accompanying class. By convention, you should capitalize the first letter of the names of these classes within the .py file. For example, in the ride.py file, define a Ride class. For now, the classes need not do anything, just write the keyword pass on the first line under each of your class definitions._

as these files already exist.

Possible resolutions:
- remove files from master branch
- change instructions

**Comment by sumedh10** [comment]
@climatebrad Thanks for reporting, this is now fixed!
